<?php
// Heading
$_['heading_title']                	= 'SEO generator';
$_['text_1']                	= 'Generated by: ';
$_['text_2']                	= ' second(s)';
$_['text_3']                	= 'Back';

$_['heading_products']                	= 'Products';
$_['heading_categ']                	= 'Categories';
$_['heading_manuf']                	= 'Brands';
$_['heading_info']                	= 'Infopages';
$_['text_generate']                	= 'Generate';
$_['text_h1']                	= 'Heading Title (Н1)';
$_['text_title']                	= 'Document Title';
$_['text_meta_kw']                	= 'Meta-Keywords';
$_['text_meta_desc']                	= 'Meta Tag Description';
$_['text_pattern_pro']                	= 'Available patterns:{name}, {model}, {price}, {catname}, {brand}';
$_['text_pattern_cat']                	= 'Available patterns:{name}, {min}, {max}, {store}, {brand}';
$_['text_seo_rewr']                	= 'Generate and rewrite current SEO-url';
$_['text_seo_warn']                	= 'WARNING!!! If checked, all seo-URL will be rewrited';

?>